
modLoader="javafml" #mandatory

loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

issueTrackerURL="https://github.com/SrGnis/Creeper_AI_Updated/issues" #optional

[[mods]] #mandatory

modId="creeperaiupdated" #mandatory

version="1.1" #mandatory

displayName="Creeper AI Updated" #mandatory

updateJSONURL="http://myurl.me/" #optional

displayURL="https://www.curseforge.com/minecraft/mc-mods/creeper-ai-updated" #optional

logoFile="logo.png" #optional

credits="Mod inspired by the work of Funwayguy in his mod Epic Siege Mod" #optional

authors="SrGnis" #optional

description='''Gives creepers the ability of see trough walls, spawn powered and explode if they cant reach you, destroying obstacles and walls.'''

[[dependencies.creeperaiupdated]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"

# Here's another dependency
[[dependencies.creeperaiupdated]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
