name: Fabric Build

on:
  push:
    branches:
    - master
    paths:
    - 'fabric/**'
  workflow_dispatch:

jobs:
  build_fabric:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.17
      uses: actions/setup-java@v1
      with:
        java-version: 1.17
    - name: Grant execute permission for gradlew
      run: chmod +x fabric/gradlew
    - name: Build with Gradle
      run: cd fabric && ./gradlew build
    - uses: actions/upload-artifact@v2.2.4
      with:
        name: creeperaiupdated_fabric
        path: ./fabric/build/libs/*
