name: Forge Build

on:
  push:
    branches:
    - master
    paths:
    - 'forge/**'
  workflow_dispatch:

jobs:
  build_forge:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.16
      uses: actions/setup-java@v1
      with:
        java-version: 1.16
    - name: Grant execute permission for gradlew
      run: chmod +x forge/gradlew
    - name: Build with Gradle
      run: cd forge && ./gradlew build
    - uses: actions/upload-artifact@v2.2.4
      with:
        name: creeperaiupdated_forge
        path: ./forge/build/libs/*
